enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  f267ee68-5a8d-40eb-8e2c-c1392a597451:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
